### ISSUE TITLE
Miscellaneous changes in readme

### ISSUE THREAD

**Issue by evanessa234** [incubateind/fellows#3]
While reading the current readme file I encountered few spelling errors, few repeated words, etc.

_For example:_
- “basis or scoring”
- “website will have have a leaderboard”

**Comment by evanessa234** [comment]
@kroy96 If mentioned changes are to be applied, can I help with it?

**Comment by kroy96** [comment]
Hi @evanessa234 sure you make the changes. Appreciate it.
